### ISSUE TITLE
Problems loading and saving second screen

### ISSUE THREAD

**Issue by MilanPolle** [lantzelot-swe/PCUGameManager#4]
[Screen2SavingError.txt](https://github.com/lantzelot-swe/PCUGameManager/files/5862696/Screen2SavingError.txt)

I'm getting this error a lot when saving game information after adding a second screen. The screen image should have been loaded in the first place when selecting the game, as it was already there, but it shows as missing.
Only tested with VIC-20 games, don't know if that makes a difference.

**Comment by lantzelot-swe** [comment]
Thanks for reporting, I think I have solved this already in the upcoming 1.2.0 release. How did you add the games to the game manager? Did you import them from an existing directory or did you use the scraper?

I found an issue where the game manager assumed that screenshots and covers had the names defined by the maxi game tool, if the files where named in a different way it could not rename the files when saving, thus saying that they are missing. I think this is the issue here.

**Comment by lantzelot-swe** [comment]
I think this is solved in versino 1.2.0, please try it out.

**Comment by MilanPolle** [comment]
Wow, that was fast. I'll try the new version. I did import them from a backup of the files on my stick.

**Comment by MilanPolle** [comment]
Sadly the problem is still there. I select a game that doesn't have a second screenshot (even though it is there on disk), select an image for it (which has the exact name used by PCUAE already), then select another game, the application will ask me if I want to save the changes and that's when the error pops up.

Maybe it is trying to save over an existing image but it still has that file locked from failing to load it for some reason? The screenshot is there already in the screens folder of the game manager.

**Comment by lantzelot-swe** [comment]
Is it a specific screenshot or does it happen all the time? Can you perhaps attach a screenshot file  that fails here so I can have a look if there is some format problems?

**Comment by MilanPolle** [comment]
![SPIDERSOFMARS-01](https://user-images.githubusercontent.com/12609997/106188215-f81c4600-61a6-11eb-97de-7801e78dd5a4.png)
![ROBOTPANIC-01](https://user-images.githubusercontent.com/12609997/106188360-2ac63e80-61a7-11eb-8645-694bb5c49427.png)
![JELLYMONSTERS-01](https://user-images.githubusercontent.com/12609997/106188497-52b5a200-61a7-11eb-9e24-c31cd603d5e1.png)
![GORF-01](https://user-images.githubusercontent.com/12609997/106188652-85f83100-61a7-11eb-9221-d060c042631b.png)

It happens every time. But somehow not with all games.
I just found out that if I change the description text instead of adding the screenshot and then select another game, I get a pop-up telling me "The following information needs to be added before saving: Screenshot 2".

**Comment by lantzelot-swe** [comment]
I found the problem, it was nothing wrong with the png images. Some tsg files in PCU does not define two screenshots, the game manager did not handle this very well when a game was imported. I have fixed so that it's possible to add a second screenshot now for such games, included in version 1.2.1.

**Comment by MilanPolle** [comment]
Awesome! I can confirm that this is working perfectly now, good job!
